import swaggerJsdoc from 'swagger-jsdoc';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.1.0',
    info: {
      title: 'School Management API',
      version: '1.0.0',
      description: 'Multi-tenant SaaS School Management System API',
    },
    servers: [
      { url: '/api/v1', description: 'API v1' },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
      schemas: {
        Error: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            error: {
              type: 'object',
              properties: {
                code: { type: 'string', example: 'VALIDATION_ERROR' },
                message: { type: 'string', example: 'Invalid input' },
                details: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      path: { type: 'string' },
                      message: { type: 'string' },
                    },
                  },
                },
              },
            },
          },
        },
        PaginationMeta: {
          type: 'object',
          properties: {
            page: { type: 'integer', example: 1 },
            limit: { type: 'integer', example: 20 },
            total: { type: 'integer', example: 100 },
            totalPages: { type: 'integer', example: 5 },
          },
        },
        // ---- User & Auth Schemas ----
        UserResponse: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            email: { type: 'string', format: 'email' },
            phone: { type: 'string', nullable: true },
            isActive: { type: 'boolean' },
            teacherId: { type: 'string', format: 'uuid', nullable: true },
            studentId: { type: 'string', format: 'uuid', nullable: true },
            guardianId: { type: 'string', format: 'uuid', nullable: true },
            lastLoginAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            roles: {
              type: 'array',
              items: { $ref: '#/components/schemas/UserRole' },
            },
          },
        },
        UserRole: {
          type: 'object',
          properties: {
            role: { $ref: '#/components/schemas/Role' },
            schoolId: { type: 'string', format: 'uuid', nullable: true },
          },
        },
        // ---- School Schema ----
        School: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Springfield High School' },
            code: { type: 'string', example: 'springfield-hs' },
            logoUrl: { type: 'string', format: 'uri', nullable: true },
            timezone: { type: 'string', example: 'America/New_York' },
            defaultLocale: { type: 'string', example: 'en' },
            currency: { type: 'string', example: 'USD' },
            country: { type: 'string', nullable: true },
            city: { type: 'string', nullable: true },
            address: { type: 'string', nullable: true },
            phone: { type: 'string', nullable: true },
            email: { type: 'string', format: 'email', nullable: true },
            website: { type: 'string', format: 'uri', nullable: true },
            subscriptionPlan: { type: 'string', enum: ['free', 'basic', 'premium', 'enterprise'] },
            subscriptionExpiresAt: { type: 'string', format: 'date-time', nullable: true },
            status: { type: 'string', enum: ['active', 'suspended', 'archived'] },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        // ---- Role Schema ----
        Role: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'School Admin' },
            schoolId: { type: 'string', format: 'uuid', nullable: true },
            isSystem: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            permissions: {
              type: 'array',
              items: { $ref: '#/components/schemas/Permission' },
            },
          },
        },
        Permission: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'students.view' },
            description: { type: 'string' },
            category: { type: 'string', example: 'students' },
          },
        },
        // ---- Student Schema ----
        Student: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            studentCode: { type: 'string', example: 'STU-2024-001' },
            firstName: { type: 'string', example: 'John' },
            lastName: { type: 'string', example: 'Doe' },
            dateOfBirth: { type: 'string', format: 'date' },
            gender: { type: 'string', enum: ['male', 'female'] },
            nationalId: { type: 'string', nullable: true },
            nationality: { type: 'string', nullable: true },
            religion: { type: 'string', nullable: true },
            bloodType: { type: 'string', enum: ['A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG'], nullable: true },
            address: { type: 'string', nullable: true },
            phone: { type: 'string', nullable: true },
            email: { type: 'string', format: 'email', nullable: true },
            photoUrl: { type: 'string', format: 'uri', nullable: true },
            medicalNotes: { type: 'string', nullable: true },
            status: { type: 'string', enum: ['active', 'graduated', 'withdrawn', 'suspended', 'transferred'] },
            admissionDate: { type: 'string', format: 'date' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        // ---- Teacher Schema ----
        Teacher: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            teacherCode: { type: 'string', example: 'TCH-001' },
            firstName: { type: 'string', example: 'Jane' },
            lastName: { type: 'string', example: 'Smith' },
            gender: { type: 'string', enum: ['male', 'female'] },
            nationalId: { type: 'string', nullable: true },
            phone: { type: 'string', nullable: true },
            email: { type: 'string', format: 'email', nullable: true },
            specialization: { type: 'string', nullable: true },
            qualification: { type: 'string', nullable: true },
            photoUrl: { type: 'string', format: 'uri', nullable: true },
            status: { type: 'string', enum: ['active', 'on_leave', 'resigned', 'terminated'] },
            hireDate: { type: 'string', format: 'date' },
            departmentId: { type: 'string', format: 'uuid', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        // ---- Guardian & Enrollment Schemas ----
        Guardian: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            firstName: { type: 'string', example: 'Mary' },
            lastName: { type: 'string', example: 'Johnson' },
            gender: { type: 'string', enum: ['male', 'female'], nullable: true },
            nationalId: { type: 'string', nullable: true },
            phone: { type: 'string', example: '+1234567890' },
            email: { type: 'string', format: 'email', nullable: true },
            occupation: { type: 'string', nullable: true },
            address: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Enrollment: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            studentId: { type: 'string', format: 'uuid' },
            classSectionId: { type: 'string', format: 'uuid' },
            academicYearId: { type: 'string', format: 'uuid' },
            status: { type: 'string', enum: ['active', 'completed', 'withdrawn', 'transferred'] },
            enrollmentDate: { type: 'string', format: 'date' },
            completionDate: { type: 'string', format: 'date', nullable: true },
            rollNumber: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        // ---- Exam & Grading Schemas ----
        Exam: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            academicYearId: { type: 'string', format: 'uuid' },
            termId: { type: 'string', format: 'uuid' },
            gradingScaleId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Midterm Exam 2024' },
            examType: { type: 'string', enum: ['quiz', 'midterm', 'final', 'assignment', 'practical'] },
            weight: { type: 'number', example: 30 },
            startDate: { type: 'string', format: 'date', nullable: true },
            endDate: { type: 'string', format: 'date', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ExamSubject: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            examId: { type: 'string', format: 'uuid' },
            subjectId: { type: 'string', format: 'uuid' },
            maxMarks: { type: 'number', example: 100 },
            passingMarks: { type: 'number', example: 40 },
            weight: { type: 'number', example: 1.0, description: 'Weight of this subject in the overall exam' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        GradingScale: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Standard Grading' },
            minPassingScore: { type: 'number', example: 60 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        GradeDefinition: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            gradingScaleId: { type: 'string', format: 'uuid' },
            letter: { type: 'string', example: 'A' },
            minScore: { type: 'number', example: 90 },
            maxScore: { type: 'number', example: 100 },
            gpa: { type: 'number', example: 4.0, nullable: true },
            description: { type: 'string', example: 'Excellent', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        StudentGrade: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            examSubjectId: { type: 'string', format: 'uuid' },
            studentId: { type: 'string', format: 'uuid' },
            score: { type: 'number', example: 85.5 },
            grade: { type: 'string', example: 'A', nullable: true },
            remarks: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ReportCard: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            studentId: { type: 'string', format: 'uuid' },
            academicYearId: { type: 'string', format: 'uuid' },
            termId: { type: 'string', format: 'uuid', nullable: true },
            gpa: { type: 'number', example: 3.75, nullable: true },
            totalScore: { type: 'number', example: 750.00, nullable: true },
            maxScore: { type: 'number', example: 800.00, nullable: true },
            percentage: { type: 'number', example: 93.75, nullable: true },
            rank: { type: 'integer', example: 5, nullable: true, description: 'Rank in class or grade' },
            remarks: { type: 'string', nullable: true },
            publishedAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        // ---- Fee & Finance Schemas ----
        FeeInvoice: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            studentId: { type: 'string', format: 'uuid' },
            invoiceNumber: { type: 'string', example: 'INV-2024-0001' },
            status: { type: 'string', enum: ['draft', 'issued', 'partially_paid', 'paid', 'overdue', 'cancelled'] },
            dueDate: { type: 'string', format: 'date' },
            subtotal: { type: 'number', example: 1000.00 },
            discountAmount: { type: 'number', example: 50.00 },
            taxAmount: { type: 'number', example: 95.00 },
            netAmount: { type: 'number', example: 1045.00 },
            paidAmount: { type: 'number', example: 500.00 },
            balanceAmount: { type: 'number', example: 545.00 },
            issuedAt: { type: 'string', format: 'date-time', nullable: true },
            cancelledAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        FeePayment: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            invoiceId: { type: 'string', format: 'uuid' },
            amount: { type: 'number', example: 500.00 },
            paymentMethod: { type: 'string', enum: ['cash', 'bank_transfer', 'credit_card', 'mobile_money', 'cheque'] },
            transactionRef: { type: 'string', nullable: true },
            paidAt: { type: 'string', format: 'date-time' },
            notes: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        FeeCategory: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Tuition Fee' },
            description: { type: 'string', nullable: true },
            amount: { type: 'number', example: 5000.00, description: 'Default amount for this category' },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        FeeStructure: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            gradeId: { type: 'string', format: 'uuid' },
            academicYearId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Grade 10 Fee Structure 2024' },
            termId: { type: 'string', format: 'uuid', nullable: true },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        FeeDiscount: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Sibling Discount' },
            description: { type: 'string', nullable: true },
            type: { type: 'string', enum: ['percentage', 'fixed_amount'], example: 'percentage' },
            value: { type: 'number', example: 10.00, description: 'Percentage (10 = 10%) or fixed amount' },
            isActive: { type: 'boolean', example: true },
            validFrom: { type: 'string', format: 'date', nullable: true },
            validUntil: { type: 'string', format: 'date', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        FinancialReport: {
          type: 'object',
          properties: {
            reportType: { type: 'string', enum: ['income', 'outstanding', 'summary'], example: 'income' },
            startDate: { type: 'string', format: 'date' },
            endDate: { type: 'string', format: 'date' },
            totalIncome: { type: 'number', example: 125000.00 },
            totalOutstanding: { type: 'number', example: 45000.00 },
            totalInvoices: { type: 'integer', example: 350 },
            totalPayments: { type: 'integer', example: 280 },
            summary: {
              type: 'object',
              additionalProperties: true,
              description: 'Detailed breakdown by category, grade, or payment method',
            },
          },
        },
        // ---- Attendance Schemas ----
        StudentAttendance: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            studentId: { type: 'string', format: 'uuid' },
            date: { type: 'string', format: 'date' },
            status: { type: 'string', enum: ['present', 'absent', 'late', 'excused'] },
            lessonId: { type: 'string', format: 'uuid', nullable: true },
            remarks: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        TeacherAttendance: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            teacherId: { type: 'string', format: 'uuid' },
            date: { type: 'string', format: 'date' },
            status: { type: 'string', enum: ['present', 'absent', 'late', 'on_leave'] },
            checkInTime: { type: 'string', format: 'time', nullable: true },
            checkOutTime: { type: 'string', format: 'time', nullable: true },
            remarks: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        TeacherAvailability: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            teacherId: { type: 'string', format: 'uuid' },
            dayOfWeek: { type: 'integer', minimum: 0, maximum: 6, example: 1, description: '0=Sunday, 1=Monday, ..., 6=Saturday' },
            timeSlotId: { type: 'string', format: 'uuid', nullable: true },
            isAvailable: { type: 'boolean', example: true },
            reason: { type: 'string', nullable: true, description: 'Reason for unavailability' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        TeacherLeave: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            teacherId: { type: 'string', format: 'uuid' },
            leaveType: { type: 'string', enum: ['sick', 'personal', 'vacation', 'emergency', 'other'], example: 'sick' },
            startDate: { type: 'string', format: 'date' },
            endDate: { type: 'string', format: 'date' },
            reason: { type: 'string', nullable: true },
            status: { type: 'string', enum: ['pending', 'approved', 'rejected', 'cancelled'], example: 'pending' },
            approvedBy: { type: 'string', format: 'uuid', nullable: true },
            approvedAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        // ---- Timetable & Scheduling Schemas ----
        Lesson: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            classSectionId: { type: 'string', format: 'uuid' },
            subjectId: { type: 'string', format: 'uuid' },
            teacherId: { type: 'string', format: 'uuid' },
            timeSlotId: { type: 'string', format: 'uuid' },
            roomId: { type: 'string', format: 'uuid', nullable: true },
            dayOfWeek: { type: 'integer', minimum: 0, maximum: 6 },
            effectiveFrom: { type: 'string', format: 'date' },
            effectiveUntil: { type: 'string', format: 'date', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Substitution: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            lessonId: { type: 'string', format: 'uuid' },
            date: { type: 'string', format: 'date' },
            originalTeacherId: { type: 'string', format: 'uuid' },
            substituteTeacherId: { type: 'string', format: 'uuid' },
            reason: { type: 'string', nullable: true },
            status: { type: 'string', enum: ['pending', 'confirmed', 'completed', 'cancelled'] },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        // ---- Academic Structure Schemas ----
        AcademicYear: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: '2024-2025' },
            startDate: { type: 'string', format: 'date' },
            endDate: { type: 'string', format: 'date' },
            status: { type: 'string', enum: ['draft', 'active', 'completed'] },
            isActive: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Term: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            academicYearId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'First Term' },
            number: { type: 'integer', example: 1 },
            startDate: { type: 'string', format: 'date' },
            endDate: { type: 'string', format: 'date' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Department: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Science Department' },
            code: { type: 'string', example: 'SCI', nullable: true },
            description: { type: 'string', nullable: true },
            headOfDepartment: { type: 'string', format: 'uuid', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Grade: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Grade 10' },
            level: { type: 'integer', example: 10 },
            capacity: { type: 'integer', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Subject: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Mathematics' },
            code: { type: 'string', example: 'MATH101' },
            category: { type: 'string', enum: ['core', 'elective', 'vocational'], nullable: true },
            description: { type: 'string', nullable: true },
            departmentId: { type: 'string', format: 'uuid', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ClassSection: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            gradeId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Section A' },
            capacity: { type: 'integer', example: 40 },
            roomId: { type: 'string', format: 'uuid', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        // ---- Time & Space Schemas ----
        PeriodSet: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Regular Schedule' },
            description: { type: 'string', nullable: true },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        WorkingDay: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            periodSetId: { type: 'string', format: 'uuid' },
            dayOfWeek: { type: 'integer', minimum: 0, maximum: 6, example: 1, description: '0=Sunday, 1=Monday, ..., 6=Saturday' },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Period: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            workingDayId: { type: 'string', format: 'uuid' },
            periodNumber: { type: 'integer', example: 1 },
            name: { type: 'string', example: 'Period 1' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        TimeSlot: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            periodId: { type: 'string', format: 'uuid' },
            startTime: { type: 'string', format: 'time', example: '08:00:00' },
            endTime: { type: 'string', format: 'time', example: '09:00:00' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Room: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            roomNumber: { type: 'string', example: 'A101' },
            building: { type: 'string', example: 'Main Building', nullable: true },
            floor: { type: 'integer', example: 1, nullable: true },
            capacity: { type: 'integer', example: 40 },
            roomType: { type: 'string', enum: ['classroom', 'laboratory', 'library', 'auditorium', 'gym', 'other'], example: 'classroom' },
            facilities: { type: 'string', example: 'Projector, Whiteboard', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        RoomSubject: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            roomId: { type: 'string', format: 'uuid' },
            subjectId: { type: 'string', format: 'uuid' },
            suitabilityScore: { type: 'integer', minimum: 1, maximum: 10, example: 8, description: 'How suitable is this room for this subject' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        // ---- Dashboard Schemas ----
        DashboardOverview: {
          type: 'object',
          properties: {
            totalStudents: { type: 'integer', example: 450 },
            totalTeachers: { type: 'integer', example: 45 },
            totalClasses: { type: 'integer', example: 18 },
            activeEnrollments: { type: 'integer', example: 432 },
          },
        },
        AttendanceToday: {
          type: 'object',
          properties: {
            studentStats: {
              type: 'object',
              properties: {
                present: { type: 'integer' },
                absent: { type: 'integer' },
                late: { type: 'integer' },
                excused: { type: 'integer' },
                rate: { type: 'number', format: 'float' },
              },
            },
            teacherStats: {
              type: 'object',
              properties: {
                present: { type: 'integer' },
                absent: { type: 'integer' },
                late: { type: 'integer' },
                onLeave: { type: 'integer' },
                rate: { type: 'number', format: 'float' },
              },
            },
          },
        },
        FeesSummary: {
          type: 'object',
          properties: {
            totalInvoiced: { type: 'number', format: 'float', example: 150000.00 },
            totalCollected: { type: 'number', format: 'float', example: 120000.00 },
            totalOutstanding: { type: 'number', format: 'float', example: 30000.00 },
            collectionRate: { type: 'number', format: 'float', example: 80.0 },
            overdueCount: { type: 'integer', example: 15 },
          },
        },
        // ---- Communication Schemas ----
        Announcement: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            title: { type: 'string', example: 'School Closure Notice' },
            content: { type: 'string', description: 'Announcement content/message' },
            priority: { type: 'string', enum: ['low', 'normal', 'high', 'urgent'], example: 'normal' },
            targetAudience: { type: 'string', enum: ['all', 'students', 'teachers', 'parents', 'staff'], example: 'all' },
            publishedAt: { type: 'string', format: 'date-time', nullable: true },
            expiresAt: { type: 'string', format: 'date-time', nullable: true },
            createdBy: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Notification: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid' },
            type: { type: 'string', example: 'announcement', description: 'Notification type' },
            title: { type: 'string', example: 'New Assignment Posted' },
            message: { type: 'string', example: 'Mr. Smith posted a new assignment for Mathematics' },
            isRead: { type: 'boolean', example: false },
            metadata: { type: 'object', additionalProperties: true, nullable: true, description: 'Additional context data' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        AcademicEvent: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            schoolId: { type: 'string', format: 'uuid' },
            title: { type: 'string', example: 'Parent-Teacher Meeting' },
            description: { type: 'string', nullable: true },
            eventType: { type: 'string', enum: ['holiday', 'exam', 'meeting', 'event', 'other'], example: 'meeting' },
            startDate: { type: 'string', format: 'date' },
            endDate: { type: 'string', format: 'date', nullable: true },
            location: { type: 'string', nullable: true, example: 'School Auditorium' },
            allDay: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        // ---- System Schemas ----
        AuditLog: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid' },
            action: { type: 'string', example: 'CREATE', description: 'Action performed (CREATE, UPDATE, DELETE, etc)' },
            entityType: { type: 'string', example: 'Student', description: 'Type of entity affected' },
            entityId: { type: 'string', format: 'uuid', description: 'ID of the affected entity' },
            changes: { type: 'object', additionalProperties: true, nullable: true, description: 'Details of changes made' },
            ipAddress: { type: 'string', nullable: true, example: '192.168.1.100' },
            userAgent: { type: 'string', nullable: true },
            timestamp: { type: 'string', format: 'date-time' },
          },
        },
      },
      parameters: {
        PageParam: {
          in: 'query',
          name: 'page',
          schema: { type: 'integer', minimum: 1, default: 1 },
          description: 'Page number',
        },
        LimitParam: {
          in: 'query',
          name: 'limit',
          schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 },
          description: 'Items per page',
        },
        SearchParam: {
          in: 'query',
          name: 'search',
          schema: { type: 'string' },
          description: 'Search term',
        },
      },
      responses: {
        Unauthorized: {
          description: 'Missing or invalid authentication',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/Error' },
            },
          },
        },
        Forbidden: {
          description: 'Insufficient permissions',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/Error' },
            },
          },
        },
        NotFound: {
          description: 'Resource not found',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/Error' },
            },
          },
        },
        ValidationError: {
          description: 'Validation failed',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/Error' },
            },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }],
    tags: [
      { name: 'Auth', description: 'Authentication & authorization' },
      { name: 'Users', description: 'User management' },
      { name: 'Schools', description: 'School management' },
      { name: 'Roles', description: 'Role management' },
      { name: 'Academic Years', description: 'Academic year management' },
      { name: 'Terms', description: 'Term management' },
      { name: 'Departments', description: 'Department management' },
      { name: 'Grades', description: 'Grade management' },
      { name: 'Subjects', description: 'Subject management' },
      { name: 'Class Sections', description: 'Class section management' },
      { name: 'Students', description: 'Student management' },
      { name: 'Guardians', description: 'Guardian management' },
      { name: 'Enrollments', description: 'Student enrollment management' },
      { name: 'Teachers', description: 'Teacher management' },
      { name: 'Timetable', description: 'Timetable & scheduling' },
      { name: 'Substitutions', description: 'Teacher substitutions' },
      { name: 'Attendance', description: 'Student & teacher attendance' },
      { name: 'Exams', description: 'Exam management' },
      { name: 'Student Grades', description: 'Student grade records' },
      { name: 'Report Cards', description: 'Report card snapshots' },
      { name: 'Fees', description: 'Fee management & invoicing' },
      { name: 'Announcements', description: 'School announcements' },
      { name: 'Notifications', description: 'User notifications' },
      { name: 'Academic Events', description: 'Calendar events' },
      { name: 'Audit Logs', description: 'System audit trail' },
      { name: 'Self-Service', description: 'Teacher/student/guardian self-service' },
      { name: 'Dashboard', description: 'Admin dashboards' },
    ],
  },
  apis: ['./src/modules/**/*.routes.ts'],
};

export const swaggerSpec = swaggerJsdoc(options);
